name: hello-world
on: push
jobs:
  hello-world-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - run: echo "$(cat hello_world.txt)"
    
  
